# Generated by Django 4.1.3 on 2024-06-12 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rareapi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="ended_on",
        ),
    ]
