# Generated by Django 4.1.3 on 2024-06-13 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rareapi", "0002_alter_usertypechangerequest_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertypechangerequest",
            name="admin_one_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_one",
                to="rareapi.rareuser",
            ),
        ),
        migrations.AlterField(
            model_name="usertypechangerequest",
            name="admin_two_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_two",
                to="rareapi.rareuser",
            ),
        ),
    ]
