# Generated by Django 4.1.3 on 2024-06-12 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_remove_subscription_ended_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='rareapi.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts', through='rareapi.PostTag', to='rareapi.tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rare_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='rareapi.rareuser'),
        ),
    ]
